### ISSUE TITLE
import issue : export default not found

### ISSUE THREAD

**Issue by oguilleux** [cirykpopeye/selectra#25]
Hi,

When trying to import the library like so :

`import Selectra from 'selectra';`

I'm having this message :

`export 'default' (imported as 'Selectra') was not found in 'selectra' (possible exports: createSelectra)`

Can you add the class as default export as well as createSelectra please ?

Thanks

**Comment by cirykpopeye** [comment]
Dist file seperated from the actual index.js file, the only thing you need is `import { createSelectra } from 'selectra'`
